In [94]:
from openpyxl import load_workbook
import pandas as pd
import numpy as np
import re
from datetime import datetime

In [11]:
print("yes") if "hdfc" in "@jdjdjdhdfclifeis_the best bank" else print("no")

yes

In [72]:
# Reading the Excel file
wb = load_workbook('/Users/abhishekchauhan/Downloads/Kotak News Aug_updated.xlsx')

# creating the active worksheet object
ws = wb['Mentions']


# Iterate through all cells in column O
for cell in ws['J']:
    # 1. Skip empty cells to prevent errors
    if cell.value is None:
        continue
        
    cell_str = str(cell.value)
    
    # 2. Safely check if the cell contains an '=' formula and double quotes
    if cell_str.startswith('=HYPERLINK') and '"' in cell_str:
        # Extract the URL
        extracted_url = cell_str.split('"')[1]
        
        # 3. Write to Column BI on the EXACT SAME ROW (e.g., BI2, BI3, etc.)
        ws[f'BI{cell.row}'] = extracted_url
        
    elif cell.hyperlink:
        # Fallback: Just in case some cells use standard inserted hyperlinks
        ws[f'BI{cell.row}'] = cell.hyperlink.target

#convert this to pandas dataframe and save it to a new excel file
data  = list(ws.values)
columns = data[0]
rows = data[1:]
df = pd.DataFrame(rows, columns=columns)
df.columns

Index(['Mention ID', 'Date', 'Time', 'Saved at', 'Title', 'Text', 'Post type',
       'Content Types', 'Source specific format', 'URL', 'Author', 'Nickname',
       'Profile', 'Subscribers', 'Demography', 'Age', 'Source',
       'Publication place', 'Publication place profile',
       'Publication place subscribers', 'Publication place rating',
       'Resource type', 'Language', 'Country', 'Regions', 'City', 'Notes',
       'Reactions', 'Engagement', 'Likes', 'Love', 'Haha', 'Wow', 'Sad',
       'Angry', 'Care', 'Dislikes', 'Comments', 'Reposts', 'Views',
       'Impressions (owned posts)', 'Reach (owned posts)', 'Saves',
       'Potential reach', 'Rating', 'Image brands', 'Image objects',
       'Image scenes', 'Image people', 'Image activities', 'Image type',
       'Image subtype', 'Image URL', 'Assigned to', 'Processed', 'Aspects',
       'Subjects', 'Auto-categories', 'Trend', 'Tags', nan],
      dtype='str')

In [73]:
df.head()

,Mention ID,Date,Time,Saved at,Title,Text,Post type,Content Types,Source specific format,URL,...,Image subtype,Image URL,Assigned to,Processed,Aspects,Subjects,Auto-categories,Trend,Tags,NaN
0,263959706,31.08.2026,23:56,01.09.2026 13:53,Nifty outlook this week: Index may move 2-5% i...,"Updated Aug 31, 2026 23:56 IST\nIndian equity ...",Post,"Text,Image,Album",None,"=HYPERLINK(""https://www.etnownews.com/markets/...",...,NaN,"=HYPERLINK(""https://images.etnownews.com/thumb...",None,No,None,NaN,Article,None,None,https://www.etnownews.com/markets/nifty-outloo...
1,961762611,31.08.2026,23:52,01.09.2026 13:53,"Kotak Mahindra Bank के नए CEO पर फैसला जल्द, आ...","Updated Aug 31, 2026 23:52 IST\nकोटक महिंद्रा ...",Post,"Text,Image,Album",None,"=HYPERLINK(""https://hindi.etnownews.com/compan...",...,advertising,"=HYPERLINK(""https://hindiimages.etnownews.com/...",None,No,None,"Industry,Banking",NaN,None,None,https://hindi.etnownews.com/companies/kotak-ma...
2,1766397598,31.08.2026,23:45,01.09.2026 13:53,Who will lead Kotak Mahindra Bank next? Two ca...,Mutual Funds\nReturn period 1 Year 3 Year 5 Ye...,Post,"Text,Image,Album",None,"=HYPERLINK(""https://www.etnownews.com/companie...",...,advertising,"=HYPERLINK(""https://images.etnownews.com/thumb...",None,No,None,NaN,Caption,None,None,https://www.etnownews.com/companies/who-will-l...
3,4230065176,31.08.2026,22:57,01.09.2026 13:53,"NIIF infrastructure fund raises Rs 19,000 cror...",Copied\nMUMBAI: National Investment and Infras...,Post,"Text,Image,Album",None,"=HYPERLINK(""https://www.newindianexpress.com/b...",...,graphics,"=HYPERLINK(""https://cf-images.assettype.com/ne...",None,No,None,Economics,Article,None,None,https://www.newindianexpress.com/business/2026...
4,2171894352,31.08.2026,22:36,01.09.2026 13:53,"Kotak Mahindra Bank Taps Paritosh Kashyap, Anu...",The succession exercise follows Ashok Vaswani'...,Post,"Text,Image,Album",None,"=HYPERLINK(""https://www.outlookbusiness.com/co...",...,advertising,"=HYPERLINK(""https://media.assettype.com/outloo...",None,No,None,NaN,Article,None,None,https://www.outlookbusiness.com/corporate/kota...

In [74]:
df.rename(columns={np.nan: 'URL 2'}, inplace=True)

In [98]:
df.tail()

,Mention ID,Date,Time,Saved at,Title,Text,Combine text,Sentiment,Cluster,Stock,...,Image type,Image subtype,Image URL,Assigned to,Processed,Aspects,Subjects,Auto-categories,Trend,Tags
3756,2026-09-24 21:55:13/Asha/File_Name/3757,01.08.2026,10:30,01.09.2026 13:54,"ICICI Bank, Hyundai To ONGC: BofA Picks 18 Key...",Top global brokerage highlights stocks offerin...,"ICICI Bank, Hyundai To ONGC: BofA Picks 18 Key...",,,"Stocks, stocks, index, stocks, Nifty, Stocks, ...",...,NaN,NaN,"=HYPERLINK(""https://c.ndtvimg.com/2026-08/amsh...",None,No,None,"Business,Economics",Article,None,None
3757,2026-09-24 21:55:13/Asha/File_Name/3758,01.08.2026,10:30,01.09.2026 13:54,"ICICI Bank, Hyundai To ONGC: BofA Picks 18 Key...",Top global brokerage highlights stocks offerin...,"ICICI Bank, Hyundai To ONGC: BofA Picks 18 Key...",,,"Stocks, stocks, index, stocks, Nifty, Stocks, ...",...,NaN,NaN,"=HYPERLINK(""https://c.ndtvimg.com/2026-08/amsh...",None,No,None,"Business,Economics",Article,None,None
3758,2026-09-24 21:55:13/Asha/File_Name/3759,01.08.2026,10:00,01.09.2026 13:54,Talent tracker of the week: Top executive appo...,New Delhi: India witnessed a busy week of seni...,Talent tracker of the week: Top executive appo...,,,trade,...,ILLUSTRATION,graphics,"=HYPERLINK(""https://img-cdn.publive.online/fit...",None,No,None,Business,Article,None,None
3759,2026-09-24 21:55:13/Asha/File_Name/3760,01.08.2026,07:30,01.09.2026 13:54,Corporate earnings are beating estimates. Why ...,Surpassing Street expectations\nCompanies in t...,Corporate earnings are beating estimates. Why ...,,,"Nifty, index, Nifty, Nifty, stocks, stock, stock",...,PHOTO,NaN,"=HYPERLINK(""https://images.indianexpress.com/2...",None,No,None,Economics,Article,None,None
3760,2026-09-24 21:55:13/Asha/File_Name/3761,01.08.2026,00:39,01.09.2026 13:54,Charkhi Dadri News: 2.30 लाख रुपये की ठगी करने...,आरोपी ने फर्जी पीएनबी वन एपीके एप डाउनलोड करवा...,Charkhi Dadri News: 2.30 लाख रुपये की ठगी करने...,,,,...,PHOTO,NaN,"=HYPERLINK(""https://staticimg.amarujala.com/as...",None,No,None,"Industry,Banking",NaN,None,None

In [86]:
#list_to_remove = ['Combine text', 'Sentiment', 'Cluster', 'Stock', 'Relevant']

# Adding New COlumns to the DataFrame
new_columns = ['Combine text', 'Sentiment', 'Cluster', 'Stock', 'Relevant']

df['Combine text'] = df['Title'].astype(str) + ' ' + df['Text'].astype(str)
df['Sentiment'] = ''
df['Cluster'] = ''
df['Stock'] = ''
df['Relevant'] = ''

# performing the regx 


pattern = re.compile(
    r'\b(?:mutual\s*fund|stocks?|shares?|nifty|sensex|trade|mutualfund|gdp|index|nse|bse|equity)\b'
    r'|शेयर|સેન્સેક્સ|मार्केट|निफ्टी|सेंसेक्स|स्टॉक्स',
    re.IGNORECASE
)

def find_stock_terms(x):
    if pd.isna(x):
        return ''
    return ', '.join(pattern.findall(str(x)))

df['Stock'] = df['Combine text'].apply(find_stock_terms)

In [91]:
df.columns

Index(['Mention ID', 'Date', 'Time', 'Saved at', 'Title', 'Text', 'Post type',
       'Content Types', 'Source specific format', 'URL', 'Author', 'Nickname',
       'Profile', 'Subscribers', 'Demography', 'Age', 'Source',
       'Publication place', 'Publication place profile',
       'Publication place subscribers', 'Publication place rating',
       'Resource type', 'Language', 'Country', 'Regions', 'City', 'Notes',
       'Reactions', 'Engagement', 'Likes', 'Love', 'Haha', 'Wow', 'Sad',
       'Angry', 'Care', 'Dislikes', 'Comments', 'Reposts', 'Views',
       'Impressions (owned posts)', 'Reach (owned posts)', 'Saves',
       'Potential reach', 'Rating', 'Image brands', 'Image objects',
       'Image scenes', 'Image people', 'Image activities', 'Image type',
       'Image subtype', 'Image URL', 'Assigned to', 'Processed', 'Aspects',
       'Subjects', 'Auto-categories', 'Trend', 'Tags', 'URL 2', 'Combine text',
       'Sentiment', 'Cluster', 'Stock', 'Relevant'],
      dtype='str')

In [92]:
df= df[['Mention ID', 'Date', 'Time', 'Saved at', 'Title', 'Text','Combine text',
       'Sentiment', 'Cluster', 'Stock', 'Relevant', 'Post type',
       'Content Types', 'Source specific format', 'URL','URL 2', 'Author', 'Nickname',
       'Profile', 'Subscribers', 'Demography', 'Age', 'Source',
       'Publication place', 'Publication place profile',
       'Publication place subscribers', 'Publication place rating',
       'Resource type', 'Language', 'Country', 'Regions', 'City', 'Notes',
       'Reactions', 'Engagement', 'Likes', 'Love', 'Haha', 'Wow', 'Sad',
       'Angry', 'Care', 'Dislikes', 'Comments', 'Reposts', 'Views',
       'Impressions (owned posts)', 'Reach (owned posts)', 'Saves',
       'Potential reach', 'Rating', 'Image brands', 'Image objects',
       'Image scenes', 'Image people', 'Image activities', 'Image type',
       'Image subtype', 'Image URL', 'Assigned to', 'Processed', 'Aspects',
       'Subjects', 'Auto-categories', 'Trend', 'Tags', ]]

In [97]:
file_name = "File_Name"   # <- set this once

current_dt = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

df['Mention ID'] = [
    f"{current_dt}/Asha/{file_name}/{i}" 
    for i in range(1, len(df) + 1)
]

In [90]:
df.to_excel('/Users/abhishekchauhan/Downloads/Kotak News Aug_updated232.xlsx', index=False)

/var/folders/zq/6tyr5bd55nz5m1lxswhltzl00000gn/T/ipykernel_52541/4237152867.py:1: UserWarning: Cell contents too long (32774), truncated to 32767 characters
  df.to_excel('/Users/abhishekchauhan/Downloads/Kotak News Aug_updated232.xlsx', index=False)
/var/folders/zq/6tyr5bd55nz5m1lxswhltzl00000gn/T/ipykernel_52541/4237152867.py:1: UserWarning: Cell contents too long (32781), truncated to 32767 characters
  df.to_excel('/Users/abhishekchauhan/Downloads/Kotak News Aug_updated232.xlsx', index=False)
/var/folders/zq/6tyr5bd55nz5m1lxswhltzl00000gn/T/ipykernel_52541/4237152867.py:1: UserWarning: Cell contents too long (32856), truncated to 32767 characters
  df.to_excel('/Users/abhishekchauhan/Downloads/Kotak News Aug_updated232.xlsx', index=False)
/var/folders/zq/6tyr5bd55nz5m1lxswhltzl00000gn/T/ipykernel_52541/4237152867.py:1: UserWarning: Cell contents too long (32782), truncated to 32767 characters
  df.to_excel('/Users/abhishekchauhan/Downloads/Kotak News Aug_updated232.xlsx', index=False)
/var/folders/zq/6tyr5bd55nz5m1lxswhltzl00000gn/T/ipykernel_52541/4237152867.py:1: UserWarning: Cell contents too long (32787), truncated to 32767 characters
  df.to_excel('/Users/abhishekchauhan/Downloads/Kotak News Aug_updated232.xlsx', index=False)
/var/folders/zq/6tyr5bd55nz5m1lxswhltzl00000gn/T/ipykernel_52541/4237152867.py:1: UserWarning: Cell contents too long (32793), truncated to 32767 characters
  df.to_excel('/Users/abhishekchauhan/Downloads/Kotak News Aug_updated232.xlsx', index=False)
/var/folders/zq/6tyr5bd55nz5m1lxswhltzl00000gn/T/ipykernel_52541/4237152867.py:1: UserWarning: Cell contents too long (32863), truncated to 32767 characters
  df.to_excel('/Users/abhishekchauhan/Downloads/Kotak News Aug_updated232.xlsx', index=False)